const STORAGE_KEY = "adlapp-server-inventory";

export const initialServers = [
  {
    id: "dc01",
    hostname: "DC01",
    ip: "192.168.1.10",
    mac: "00-15-5D-01-10-01",
    type: "Domain Controller",
    os: "Windows Server 2022",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Online",
    owner: "John Addo",
    cpu: "4 vCPU",
    ram: "16 GB",
    storage: "250 GB",
    uptime: "47 days",
    services: ["AD DS", "DNS Server", "DHCP", "NTP"],
    health: "Healthy",
    backup: "Protected",
    isLocal: true,
    events: [
      {
        time: "Today 08:42",
        event: "Directory service replication completed",
        severity: "Info",
      },
      {
        time: "Yesterday 22:15",
        event: "Windows Update requires a restart",
        severity: "Warning",
      },
    ],
  },
  {
    id: "dc02",
    hostname: "DC02",
    ip: "192.168.1.11",
    mac: "00-15-5D-01-10-02",
    type: "Domain Controller",
    os: "Windows Server 2019",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Online",
    owner: "John Addo",
    cpu: "4 vCPU",
    ram: "16 GB",
    storage: "250 GB",
    uptime: "12 days",
    services: ["AD DS", "DNS Server", "File Replication"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Today 07:30",
        event: "SYSVOL replication healthy",
        severity: "Info",
      },
    ],
  },
  {
    id: "dhcp01",
    hostname: "DHCP01",
    ip: "192.168.1.12",
    mac: "00-15-5D-01-10-03",
    type: "DHCP Server",
    os: "Windows Server 2022",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Warning",
    owner: "Ama Boateng",
    cpu: "2 vCPU",
    ram: "8 GB",
    storage: "120 GB",
    uptime: "31 days",
    services: ["DHCP", "DNS Forwarder"],
    health: "Degraded",
    backup: "Protected",
    events: [
      {
        time: "Today 09:10",
        event: "Address pool is 82% utilized",
        severity: "Warning",
      },
    ],
  },
  {
    id: "file01",
    hostname: "FILE01",
    ip: "192.168.1.20",
    mac: "00-15-5D-01-20-01",
    type: "File Server",
    os: "Windows Server 2022",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "Physical",
    status: "Online",
    owner: "Kwame Mensah",
    cpu: "8 cores",
    ram: "32 GB",
    storage: "4 TB RAID 5",
    uptime: "93 days",
    services: ["SMB Shares", "DFS", "FSRM"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Today 06:00",
        event: "Incremental backup completed",
        severity: "Info",
      },
    ],
  },
  {
    id: "print01",
    hostname: "PRINT01",
    ip: "192.168.1.21",
    mac: "00-15-5D-01-20-02",
    type: "Print Server",
    os: "Windows Server 2019",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Maintenance",
    owner: "Efua Asante",
    cpu: "2 vCPU",
    ram: "8 GB",
    storage: "120 GB",
    uptime: "8 days",
    services: ["Print Spooler", "Department Queues"],
    health: "Maintenance",
    backup: "Protected",
    events: [
      {
        time: "Today 10:00",
        event: "Scheduled printer driver maintenance",
        severity: "Info",
      },
    ],
  },
  {
    id: "backup01",
    hostname: "BACKUP01",
    ip: "192.168.1.30",
    mac: "00-15-5D-01-30-01",
    type: "Backup Server",
    os: "Ubuntu Server 24.04",
    environment: "Production",
    location: "Kumasi DR",
    virtualization: "Physical",
    status: "Online",
    owner: "John Addo",
    cpu: "8 cores",
    ram: "64 GB",
    storage: "24 TB",
    uptime: "120 days",
    services: ["Veeam Agent", "Repository", "Immutable Storage"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Yesterday 23:00",
        event: "Full backup verification passed",
        severity: "Info",
      },
    ],
  },
  {
    id: "web01",
    hostname: "WEB01",
    ip: "10.20.10.15",
    mac: "00-15-5D-02-10-01",
    type: "Web Server",
    os: "Ubuntu Server 24.04",
    environment: "Testing",
    location: "Cloud Lab",
    virtualization: "VM",
    status: "Online",
    owner: "Ama Boateng",
    cpu: "4 vCPU",
    ram: "16 GB",
    storage: "160 GB",
    uptime: "19 days",
    services: ["Nginx", "Node.js", "TLS"],
    health: "Healthy",
    backup: "Not configured",
    events: [
      {
        time: "Today 08:05",
        event: "TLS certificate has 42 days remaining",
        severity: "Warning",
      },
    ],
  },
  {
    id: "app01",
    hostname: "APP01",
    ip: "10.20.10.20",
    mac: "00-15-5D-02-10-02",
    type: "Application Server",
    os: "Windows Server 2022",
    environment: "Development",
    location: "Cloud Lab",
    virtualization: "VM",
    status: "Offline",
    owner: "Kwame Mensah",
    cpu: "4 vCPU",
    ram: "16 GB",
    storage: "250 GB",
    uptime: "0 days",
    services: ["IIS", "Application Service"],
    health: "Unavailable",
    backup: "Not configured",
    events: [
      {
        time: "Today 07:55",
        event: "Health probe did not receive a response",
        severity: "Error",
      },
    ],
  },
  {
    id: "sql01",
    hostname: "SQL01",
    ip: "192.168.2.10",
    mac: "00-15-5D-03-10-01",
    type: "SQL Database",
    os: "Windows Server 2022",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Online",
    owner: "John Addo",
    cpu: "8 vCPU",
    ram: "64 GB",
    storage: "2 TB SSD",
    uptime: "66 days",
    services: ["SQL Server", "SQL Agent", "SSRS"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Today 01:00",
        event: "Database integrity check completed",
        severity: "Info",
      },
    ],
  },
  {
    id: "esxi01",
    hostname: "ESXI01",
    ip: "192.168.3.10",
    mac: "00-15-5D-04-10-01",
    type: "VMware ESXi",
    os: "VMware ESXi 8.0",
    environment: "Production",
    location: "Kumasi DR",
    virtualization: "Physical",
    status: "Online",
    owner: "Kwame Mensah",
    cpu: "16 cores",
    ram: "128 GB",
    storage: "8 TB",
    uptime: "204 days",
    services: ["vSphere", "vMotion", "Datastore"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Today 05:30",
        event: "Host hardware sensors nominal",
        severity: "Info",
      },
    ],
  },
  {
    id: "mail01",
    hostname: "MAIL01",
    ip: "192.168.4.10",
    mac: "00-15-5D-05-10-01",
    type: "Mail Server",
    os: "Ubuntu Server 22.04",
    environment: "Production",
    location: "Accra HQ",
    virtualization: "VM",
    status: "Warning",
    owner: "Ama Boateng",
    cpu: "4 vCPU",
    ram: "16 GB",
    storage: "500 GB",
    uptime: "44 days",
    services: ["Postfix", "Dovecot", "SpamAssassin"],
    health: "Degraded",
    backup: "Protected",
    events: [
      {
        time: "Today 09:25",
        event: "Mail queue is above normal threshold",
        severity: "Warning",
      },
    ],
  },
  {
    id: "azure01",
    hostname: "AZURE-VM01",
    ip: "10.40.0.4",
    mac: "00-15-5D-06-10-01",
    type: "Azure VM",
    os: "Windows Server 2022",
    environment: "Testing",
    location: "Azure West Europe",
    virtualization: "VM",
    status: "Online",
    owner: "John Addo",
    cpu: "2 vCPU",
    ram: "8 GB",
    storage: "128 GB",
    uptime: "14 days",
    services: ["Azure Monitor", "IIS"],
    health: "Healthy",
    backup: "Protected",
    events: [
      {
        time: "Yesterday 18:10",
        event: "Azure VM agent reported ready",
        severity: "Info",
      },
    ],
  },
];

export function loadServers() {
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved ? JSON.parse(saved) : initialServers;
  } catch (error) {
    return initialServers;
  }
}

export function saveServers(servers) {
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(servers));
  } catch (error) {
    // The app remains usable when storage is unavailable.
  }
}
